// AUTO-GENERATED by scripts/build/generate-bundled-config.ts.
// Do not edit by hand. Regenerate via `npm run codegen` after editing
// the source manifest / config. CI fails on drift (see ADR-059).

// Source-of-truth: see scripts/build/generate-bundled-config.ts for the
// emit pipeline. Edit the upstream config file, not this module.

export const BUNDLED_OBSERVABILITY_CONFIG = {
  "lookbackSeconds": 86400,
  "thresholds": {
    "contributionsLifetimePerGuild": 50000,
    "contributionsLifetimePerProject": 10000,
    "costUsdPerDayPerProject": 10,
    "decisionsLifetimePerProject": 500,
    "locksHeldConcurrentPerProject": 20,
    "sessionsActivePerGuild": 100,
    "sessionsActivePerProject": 20,
    "syncLagSecondsP95": 300,
    "triagePendingBacklog": 25,
    "vectorIndexRowsPerGuild": 100000
  }
} as const;

export type BundledObservabilityConfig = typeof BUNDLED_OBSERVABILITY_CONFIG;
