// AUTO-GENERATED by scripts/build/generate-bundled-config.ts.
// Do not edit by hand. Regenerate via `npm run codegen` after editing
// the source manifest / config. CI fails on drift (see ADR-059).

// Source-of-truth: see scripts/build/generate-bundled-config.ts for the
// emit pipeline. Edit the upstream config file, not this module.

export const BUNDLED_PROTOTYPE_MANIFEST = {
  "content_path": "prototypes/dashboard-northstar",
  "name": "dashboard-northstar",
  "surfaces": [
    {
      "dps": [
        "DP-2",
        "DP-11"
      ],
      "route": "/",
      "strategy_notes": "Home is the brand surface + the cold-visitor on-ramp. The hero is a\nstatement of substrate posture (\"one canonical artifact\"); the\nreviewer sidebar is the \"show this to people\" handle that supersedes\n`for-reviewers.md` as the primary share artifact.\n"
    },
    {
      "dps": [
        "DP-1",
        "DP-3",
        "DP-7",
        "DP-13"
      ],
      "route": "/compose",
      "strategy_notes": "Compose is the wedge (DP-7). Action selector primitives:\npropose / claim / log_decision / checkpoint. Every authoring path\nlands here; no other surface authors. The territory selector is the\nonly field that requires a deliberate choice — everything else\ndefaults from context.\n"
    },
    {
      "dps": [
        "DP-1",
        "DP-4",
        "DP-6"
      ],
      "route": "/inbox",
      "strategy_notes": "Action-shaped sections (DP-1) — section headers name what's being\nasked of you, not status. Each section is a server-side query in\nthe eventual substrate (proposal.review_role x reaction_kind etc.);\nthe prototype filters fixtures locally to demonstrate the IA.\n"
    },
    {
      "dps": [
        "DP-4",
        "DP-6",
        "DP-8",
        "DP-9"
      ],
      "route": "/activity",
      "strategy_notes": "Three loops, one timeline (ADR-055). Filter chips for loop +\nauthor kind sit above the fold (DP-8). Sort defaults to recency\nwith trend-weighted as the opt-in (DP-4). Scale budget callout\n(DP-6): paginate at 50, virtualize at 500.\n"
    },
    {
      "dps": [
        "DP-2",
        "DP-8"
      ],
      "route": "/atlas",
      "strategy_notes": "Historical projection across territories. Facets are explicit\n(proposal / synthesis / contribution / decision / lock) rather\nthan auto-detected — the navigator stays declarative.\n"
    },
    {
      "dps": [
        "DP-5"
      ],
      "route": "/connect",
      "strategy_notes": "Presence + integrations. The presence chip in the harness rail\n(slice 6) is the realtime view; /connect is the deliberate\nsession-management surface (revoke / pause / lifecycle).\n"
    },
    {
      "dps": [],
      "route": "/design-system",
      "strategy_notes": "Tokens, ramp tuples, components in isolation. Internal reference;\nnot part of the canonical IA. Linked from the home reviewer\nsidebar for \"what design system is this built with?\" questions.\n"
    }
  ],
  "traceability_source": {
    "design_principles": "prototypes/dashboard-northstar/docs/design-principles.md",
    "research_dir": "prototypes/dashboard-northstar/docs/research"
  }
} as const;

export type BundledPrototypeManifest = typeof BUNDLED_PROTOTYPE_MANIFEST;
